resources:
  pipelines:
    - pipeline: integ_test_promote
      source: pre-integ-test
      trigger: true

trigger: none
pr: none

stages:
  - stage: integration_test
    displayName: Integration test
    jobs:
      - template: integ-test-promote-template.yml
        parameters:
          TASK_VERSION: ['0', '1']

  - stage: publish_prerelease
    displayName: Publish prerelease
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: ubuntu-latest
    jobs:
      - deployment: publish_prerelease
        environment: prerelease
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none

                - task: DownloadPipelineArtifact@2
                  displayName: Get stored extension
                  inputs:
                    source: specific
                    project: b3d35465-d584-454b-a4e9-e60757510c12
                    pipeline: 6
                    runVersion: latest
                    artifact: extension
                    path: $(Build.StagingDirectory)

                - task: TfxInstaller@2
                  displayName: Install tfx-cli
                  inputs:
                    version: v0.7.x

                - task: PublishAzureDevOpsExtension@2
                  displayName: Publish prerelease
                  inputs:
                    connectTo: VsTeam
                    connectedServiceName: MathWorks
                    fileType: vsix
                    extensionTag: -prerelease
                    extensionVisibility: private
                    vsixFile: $(Build.StagingDirectory)/*.vsix
                    updateTasksVersion: false

  - stage: publish_release
    displayName: Publish release
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: ubuntu-latest
    jobs:
      - deployment: publish_release
        environment: release
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none

                - task: DownloadPipelineArtifact@2
                  displayName: Get stored extension
                  inputs:
                    source: specific
                    project: b3d35465-d584-454b-a4e9-e60757510c12
                    pipeline: 6
                    runVersion: latest
                    artifact: extension
                    path: $(Build.StagingDirectory)

                - task: TfxInstaller@2
                  displayName: Install tfx-cli
                  inputs:
                    version: v0.7.x

                - task: PublishAzureDevOpsExtension@2
                  displayName: Publish release
                  inputs:
                    connectTo: VsTeam
                    connectedServiceName: MathWorks
                    fileType: vsix
                    vsixFile: $(Build.StagingDirectory)/*.vsix
                    updateTasksVersion: false
