jobs:
  - ${{ each version in parameters.TASK_VERSION }}:
    

    - job: test_run_tests_v${{ version }}
      strategy:
        matrix:
          microsoft_hosted_linux:
            poolName: Azure Pipelines
            vmImage: ubuntu-22.04
      pool:
        name: $(poolName)
        vmImage: $(vmImage)
      workspace:
        clean: all
      steps:
        - checkout: none
        - task: MathWorks.matlab-azure-devops-extension-dev.InstallMATLAB.InstallMATLAB@${{ version }}
          displayName: Install MATLAB on Microsoft-hosted agents
          condition: eq(${{ version }}, '0')
        - task: MathWorks.matlab-azure-devops-extension-dev.InstallMATLAB.InstallMATLAB@${{ version }}
          inputs:
            products: Simulink Simulink_Test Simulink_Coverage Parallel_Computing_Toolbox
          displayName: Install MATLAB on Microsoft-hosted agents
          condition: eq(${{ version }}, '1')
        - bash: |
            echo 'myvar = 123' > startup.m
            mkdir src
            echo 'function c=add(a,b);c=a+b;' > src/add.m
            mkdir tests
            echo "%% StartupTest" > tests/mytest.m
            echo "evalin('base','assert(myvar==123)')" >> tests/mytest.m
            echo "%% FirstTest" >> tests/mytest.m
            echo "assert(add(1,2)==3)" >> tests/mytest.m
            mkdir tests/filteredTest
            echo "%% simpleTest" >> tests/filteredTest/filtertest.m
            echo "assert(2==2)" >> tests/filteredTest/filtertest.m
            echo "%% FilterByTag" >> tests/filteredTest/TaggedTest.m
            cat << EOF > tests/filteredTest/TaggedTest.m
            classdef (TestTags = {'FILTERED'}) TaggedTest < matlab.unittest.TestCase
                methods(Test)
                    function testTag(testCase)
                        assert(2==2);
                    end
                end
            end
            EOF
          displayName: Make MATLAB tests
        # - task: MathWorks.matlab-azure-devops-extension-dev.RunMATLABTests.RunMATLABTests@${{ version }}
        #   displayName: Run MATLAB tests with defaults
        #   inputs:
        #     sourceFolder: src
        # - task: MathWorks.matlab-azure-devops-extension-dev.RunMATLABTests.RunMATLABTests@${{ version }}
        #   displayName: Run MATLAB tests producing artifacts
        #   inputs:
        #     testResultsJUnit: test-results/matlab/results.xml
        #     testResultsHTML:  test-results/matlab/resultsHTML
        #     codeCoverageCobertura: code-coverage/coverage.xml
        #     codeCoverageHTML: code-coverage/coverageHTML
        #     sourceFolder: src
        # - task: MathWorks.matlab-azure-devops-extension-dev.RunMATLABTests.RunMATLABTests@${{ version }}
        #   displayName: Run MATLAB tests filter by folder
        #   inputs:
        #     testResultsJUnit: test-results/matlab/selectbyfolder.xml
        #     selectByFolder: tests/filteredTest
        - task: MathWorks.matlab-azure-devops-extension-dev.RunMATLABTests.RunMATLABTests@${{ version }}
          displayName: Run MATLAB tests filter by tag
          inputs:
            testResultsJUnit: test-results/matlab/selectbytag.xml
            selectByTag: FILTERED
        - task: MathWorks.matlab-azure-devops-extension-dev.RunMATLABTests.RunMATLABTests@${{ version }}
          displayName: Run MATLAB tests filter by name
          inputs:
            testResultsJUnit: test-results/matlab/selectbyname.xml
            selectByName: "filtertest/* mytest/StartupTest"
            sourceFolder: src
          condition: not(eq(${{ version }}, '0'))
        - task: MathWorks.matlab-azure-devops-extension-dev.RunMATLABTests.RunMATLABTests@${{ version }}
          displayName: Run MATLAB tests filter by name with multiple spaces
          inputs:
            testResultsJUnit: test-results/matlab/selectbynamewithmultiplespaces.xml
            selectByName: "filtertest/*    mytest/StartupTest"
            sourceFolder: src
          condition: not(eq(${{ version }}, '0'))        
        # - bash: |
        #     set -e
        #     grep -q FirstTest test-results/matlab/results.xml
        #   displayName: Verify test results file was created
        # - bash: |
        #     set -e
        #     test -d test-results/matlab/resultsHTML
        #     test -f test-results/matlab/resultsHTML/*.html
        #   displayName: Verify HTML test results folder and HTML file was created
        #   condition: not(eq(${{ version }}, '0'))
        # - bash: |
        #     set -e
        #     grep -q add code-coverage/coverage.xml
        #   displayName: Verify code coverage file was created
        # - bash: |
        #     set -e
        #     test -d code-coverage/coverageHTML
        #     test -f code-coverage/coverageHTML/*.html
        #   displayName: Verify HTML code coverage folder and HTML file was created
        #   condition: not(eq(${{ version }}, '0'))
        # - bash: |
        #     set -e
        #     grep -q simpleTest test-results/matlab/selectbyfolder.xml
        #     grep -v FirstTest test-results/matlab/selectbyfolder.xml
        #   displayName: Verify test filtered by folder
        - bash: |
            set -e
            grep -q TaggedTest test-results/matlab/selectbytag.xml
            grep -v FirstTest test-results/matlab/selectbytag.xml
            grep -v simpleTest test-results/matlab/selectbytag.xml
          displayName: Verify test filtered by tag name
        - bash: |
            set -e
            grep -q StartupTest test-results/matlab/selectbyname.xml
            grep -q simpleTest test-results/matlab/selectbyname.xml
            ! grep -q FirstTest test-results/matlab/selectbyname.xml
          displayName: Verify test filtered by name
          condition: not(eq(${{ version }}, '0'))
        - bash: |
            set -e
            grep -q StartupTest test-results/matlab/selectbynamewithmultiplespaces.xml
            grep -q simpleTest test-results/matlab/selectbynamewithmultiplespaces.xml
            ! grep -q FirstTest test-results/matlab/selectbynamewithmultiplespaces.xml
          displayName: Verify test filtered by name with multiple spaces
          condition: not(eq(${{ version }}, '0'))
        # - bash: |
        #     echo 'diary console.log' >> startup.m
        #   displayName: Set up diary for logging
        # - task: MathWorks.matlab-azure-devops-extension-dev.RunMATLABTests.RunMATLABTests@${{ version }}
        #   displayName: Run MATLAB tests with strict checks
        #   inputs:
        #     strict: true
        #     sourceFolder: src
        # - bash: |
        #     set -e
        #     grep -q "runner.addPlugin(FailOnWarningsPlugin())" console.log
        #     rm console.log
        #   displayName: Verify tests ran with strict checks
        # Disable parallel tests until PCT bug is fixed g3416906
        # - task: MathWorks.matlab-azure-devops-extension-dev.RunMATLABTests.RunMATLABTests@${{ version }}
        #   displayName: Run MATLAB tests in parallel
        #   inputs:
        #     useParallel: true
        #     sourceFolder: src
        #   condition: not(eq(${{ version }}, '0'))
        # - bash: |
        #     set -e
        #     grep -q "Starting parallel pool (parpool)" console.log
        #     rm console.log
        #   displayName: Verify tests ran in parallel
        #   condition: not(eq(${{ version }}, '0'))
        # - task: MathWorks.matlab-azure-devops-extension-dev.RunMATLABTests.RunMATLABTests@${{ version }}
        #   displayName: Run MATLAB tests with detailed display level for event details
        #   inputs:
        #     outputDetail: Detailed
        #     sourceFolder: src
        # - bash: |
        #     set -e
        #     grep -q "('OutputDetail', 3)" console.log
        #     rm console.log
        #   displayName: Verify tests ran with detailed display level for event details
        # - task: MathWorks.matlab-azure-devops-extension-dev.RunMATLABTests.RunMATLABTests@${{ version }}
        #   displayName: Run MATLAB tests with detailed verbosity level for logged diagnostics
        #   inputs:
        #     loggingLevel: Detailed
        #     sourceFolder: src
        # - bash: |
        #     set -e
        #     grep -q "('LoggingLevel', 3)" console.log
        #     rm console.log
        #   displayName: Verify tests ran with detailed verbosity level for logged diagnostics
        - bash: |
            mkdir simtests
            cat << EOF > simtests/createModel.m
            % Create model
            model = 'new_temp_model';
            new_system(model);
            load_system(model);

            % add blocks
            add_block('built-in/Inport', [model, '/InputPort'], ...
                'Position', [50 50 100 100]);
            add_block('built-in/Gain', [model, '/Gain'], 'Gain', '1', ...
                'Position', [150 50 200 100]);
            add_block('built-in/Outport', [model, '/OutputPort'], ...
                'Position', [250 50 300 100]);

            % add lines
            add_line(model, 'InputPort/1', 'Gain/1');
            add_line(model, 'Gain/1', 'OutputPort/1');

            % save system
            save_system(model);
            close_system(model);

            % Create Simulink Test File
            sltest.testmanager.clear;
            sltest.testmanager.clearResults;
            tf = sltest.testmanager.TestFile('test.mldatx');

            % Set coverage related options.
            cs = tf.getCoverageSettings;
            cs.RecordCoverage = true;
            cs.MdlRefCoverage = true;
            cs.MetricSettings = 'd';

            % Set model and collect baseline.
            ts = tf.getTestSuites;
            tc = ts.getTestCases;
            tc.setProperty('model', model);
            captureBaselineCriteria(tc,'baseline_API.mat',true);

            % Save test file and close.
            tf.saveToFile;
            tf.close;
            sltest.testmanager.close;
            disp('Created Model and Simulink Test file to simulate the model.');
            evalin('base', 'clear all');
            EOF
          displayName: Create model file and Simulink test.
          condition: eq(variables['Agent.OS'], 'Linux')
        # - task: MathWorks.matlab-azure-devops-extension-dev.RunMATLABCommand.RunMATLABCommand@${{ version }}
        #   displayName: Run model creator and test Simulink test generator
        #   inputs:
        #     command: "cd simtests;createModel"
        #   condition: eq(variables['Agent.OS'], 'Linux')
        # - task: MathWorks.matlab-azure-devops-extension-dev.RunMATLABTests.RunMATLABTests@${{ version }}
        #   displayName: Run MATLAB tests and generate Simulink test artifacts
        #   inputs:
        #     selectByFolder: "simtests"
        #     modelCoverageCobertura: test-results/matlab/modelcoverage.xml
        #     modelCoverageHTML: test-results/matlab/modelcoverageHTML
        #     testResultsSimulinkTest: test-results/matlab/stmResult.mldatx
        #     testResultsPDF: test-results/matlab/results.pdf
        #   condition: eq(variables['Agent.OS'], 'Linux')
        # - bash: |
        #     set -e
        #     grep -q new_temp_model test-results/matlab/modelcoverage.xml
        #   displayName: Verify Model coverage was created
        #   condition: eq(variables['Agent.OS'], 'Linux')
        # - bash: |
        #     set -e
        #     test -d test-results/matlab/modelcoverageHTML
        #     test -f test-results/matlab/modelcoverageHTML/*.html
        #   displayName: Verify HTML Model coverage folder and HTML file was created
        #   condition: not(eq(${{ version }}, '0'))
        # - bash: |
        #     set -e
        #     test -f test-results/matlab/stmResult.mldatx
        #   displayName: Verify STM report was created
        #   condition: eq(variables['Agent.OS'], 'Linux')
        # - bash: |
        #     set -e
        #     test -f test-results/matlab/results.pdf
        #   displayName: Verify PDF report was created
        #   condition: eq(variables['Agent.OS'], 'Linux')
