resources:
  pipelines:
    - pipeline: integ_test_promote
      source: build-test-publish
      trigger: true

trigger: none
pr: none

stages:
  - stage: integration_test
    displayName: Integration test
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: wait_for_extension
        displayName: Wait for extension to propagate
        steps:
          - task: TfxInstaller@5
            displayName: Install tfx-cli
            inputs:
              version: v0.23.x
          - task: QueryAzureDevOpsExtensionVersion@5
            displayName: Verify dev extension version
            inputs:
              connectTo: VsTeam
              connectedServiceName: MathWorks
              publisherId: MathWorks
              extensionId: matlab-azure-devops-extension
              extensionTag: -dev
      - template: integ-test-promote-template.yml
        parameters:
          TASK_VERSION: ['0', '1']

  - stage: publish_prerelease
    displayName: Publish prerelease
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: ubuntu-latest
    jobs:
      - deployment: publish_prerelease
        environment: prerelease
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none

                - download: integ_test_promote
                  displayName: Get stored extension
                  artifact: extension

                - task: TfxInstaller@5
                  displayName: Install tfx-cli
                  inputs:
                    version: v0.23.x

                - task: PublishAzureDevOpsExtension@5
                  displayName: Publish prerelease
                  inputs:
                    connectTo: VsTeam
                    connectedServiceName: MathWorks
                    fileType: vsix
                    extensionTag: -prerelease
                    extensionVisibility: private
                    vsixFile: $(Pipeline.Workspace)/integ_test_promote/extension/*.vsix
                    updateTasksVersion: false

  - stage: publish_release
    displayName: Publish release
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: ubuntu-latest
    jobs:
      - deployment: publish_release
        environment: release
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none

                - download: integ_test_promote
                  displayName: Get stored extension
                  artifact: extension

                - task: TfxInstaller@5
                  displayName: Install tfx-cli
                  inputs:
                    version: v0.23.x

                - task: PublishAzureDevOpsExtension@5
                  displayName: Publish release
                  inputs:
                    connectTo: VsTeam
                    connectedServiceName: MathWorks
                    fileType: vsix
                    vsixFile: $(Pipeline.Workspace)/integ_test_promote/extension/*.vsix
                    updateTasksVersion: false
