resources:
  pipelines:
    - pipeline: pre_integ_test
      source: build-test-publish
      trigger:
        branches:
          - '*'

trigger: none
pr: none

pool:
  vmImage: ubuntu-16.04

steps:
  - script: sleep 60
    displayName: Wait for published extension to propagate
