resources:
  pipelines:
    - pipeline: pre_integ_test
      source: build-test-publish
      trigger: true

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
  - script: sleep 60
    displayName: Wait for published extension to propagate
