resources:
  pipelines:
    - pipeline: test_verify
      source: integ-test-promote
      trigger: true

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
  - bash: |
      echo Hello World!
      echo 123
    displayName: Print
  - bash: |
      set -e
      GET https://vsrm.dev.azure.com/{organization}/{project}/_apis/release/releases/{releaseId}?api-version=5.0
      GET https://vsrm.dev.azure.com/iat-ci-dev/matlab-azure-devops-extension/_apis/release/releases/$(Release.ReleaseId)/environments/$(Release.EnvironmentId)/deployPhases/$(Release.DeployPhaseID)/tasks/{taskId}/logs?api-version=6.0-preview.2
    displayName: get request
