resources:
  pipelines:
    - pipeline: test_verify
      source: integ-test-promote
      trigger: true

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
  - bash: |
      echo Hello World!
      echo 123
    displayName: Print
